export const GOOGLE_DEFAULT_SCRIPT_ID = 'google-ads-pixel-sdk';

export const GOOGLE_CONVERSION_EVENT_NAME = 'conversion' as const;

export const GOOGLE_CONTROL_PARAMETERS = [
  'groups',
  'send_to',
  'event_callback',
  'event_timeout',
] as const;

export const GOOGLE_CONVERSION_PROPERTIES = [
  'send_to',
  'value',
  'currency',
  'transaction_id',
] as const;

export const GOOGLE_RECOMMENDED_EVENTS = [
  'add_payment_info',
  'add_shipping_info',
  'add_to_cart',
  'add_to_wishlist',
  'begin_checkout',
  'earn_virtual_currency',
  'exception',
  'generate_lead',
  'join_group',
  'level_end',
  'level_start',
  'level_up',
  'login',
  'page_view',
  'post_score',
  'purchase',
  'refund',
  'remove_from_cart',
  'search',
  'select_content',
  'select_item',
  'select_promotion',
  'share',
  'sign_up',
  'spend_virtual_currency',
  'tutorial_begin',
  'tutorial_complete',
  'unlock_achievement',
  'view_cart',
  'view_item',
  'view_item_list',
  'view_promotion',
  'view_search_results',
] as const;

export const GOOGLE_ITEM_PARAMETERS = [
  'item_id',
  'item_name',
  'affiliation',
  'coupon',
  'creative_name',
  'creative_slot',
  'discount',
  'index',
  'item_brand',
  'item_category',
  'item_category2',
  'item_category3',
  'item_category4',
  'item_category5',
  'item_list_id',
  'item_list_name',
  'item_variant',
  'location_id',
  'price',
  'promotion_id',
  'promotion_name',
  'quantity',
] as const;

export const GOOGLE_RECOMMENDED_EVENT_PARAMETERS = [
  'achievement_id',
  'affiliation',
  'checkout_option',
  'checkout_step',
  'content_group',
  'content_id',
  'content_type',
  'coupon',
  'currency',
  'description',
  'fatal',
  'group_id',
  'items',
  'item_list_id',
  'item_list_name',
  'level',
  'method',
  'number',
  'payment_type',
  'promotions',
  'score',
  'screen_name',
  'search_term',
  'shipping',
  'shipping_tier',
  'tax',
  'transaction_id',
  'value',
  'virtual_currency_name',
] as const;
